package com.example.disclosurereview.governance.domain;

public enum ProposalRejectionReason {
    ROOT_CAUSE_WRONG, CHANGE_TOO_BROAD, BUSINESS_RULE_INCORRECT, INSUFFICIENT_EVIDENCE,
    BACKTEST_FAILED, DUPLICATE_PROPOSAL, TEMPORARY_EXCEPTION, TECHNICAL_SOLUTION_INCORRECT, OTHER
}
