package com.example.disclosurereview.model;

/** 目标产品匹配依据。 */
public enum MatchBasis {
    EXACT_PRODUCT_CODE,
    PRODUCT_CODE_IN_TABLE,
    PRODUCT_CODE_FAMILY,
    SHARE_CODE,
    EXACT_PRODUCT_NAME,
    PRODUCT_NAME_ALIAS,
    PRODUCT_NAME_SEMANTIC,
    PRODUCT_SERIES_NAME,
    MANAGER_NAME,
    ISSUER_NAME,
    DISTRIBUTOR_NAME,
    TITLE_EVIDENCE,
    SECTION_EVIDENCE,
    TABLE_ROW_EVIDENCE,
    FILENAME_DECLARATION,
    B9_DECLARATION
}
