create table rule_change_proposal_action (
    id bigint generated by default as identity primary key,
    proposal_id bigint not null,
    sequence_no integer not null,
    action_type varchar(64) not null,
    action_status varchar(64) not null,
    rule_code varchar(128),
    source_rule_version_id bigint,
    candidate_hash varchar(64),
    before_rule_snapshot_json text,
    after_rule_snapshot_json text,
    compare_result_json text,
    validation_result_json text,
    backtest_result_json text,
    affected_scope_json text,
    draft_rule_definition_id bigint,
    draft_rule_version_id bigint,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint fk_proposal_action_proposal foreign key (proposal_id)
        references rule_change_proposal(id) on delete cascade,
    constraint fk_proposal_action_source_version foreign key (source_rule_version_id)
        references review_rule_version(id) on delete set null,
    constraint fk_proposal_action_draft_rule foreign key (draft_rule_definition_id)
        references review_rule_definition(id) on delete set null,
    constraint fk_proposal_action_draft_version foreign key (draft_rule_version_id)
        references review_rule_version(id) on delete set null,
    constraint uk_proposal_action_sequence unique (proposal_id, sequence_no)
);

create index idx_proposal_action_proposal
    on rule_change_proposal_action (proposal_id, sequence_no);
create index idx_proposal_action_draft_version
    on rule_change_proposal_action (draft_rule_version_id);
