create table review_task (
    id bigint generated by default as identity primary key,
    task_no varchar(64) not null unique,
    business_record_id varchar(128),
    mail_id varchar(128),
    attachment_id varchar(128),
    original_file_name varchar(512) not null,
    stored_file_name varchar(256) not null,
    file_path varchar(1024) not null,
    file_hash varchar(64) not null,
    parameter_file_path varchar(1024),
    parameter_file_hash varchar(64),
    document_category varchar(64) not null,
    declared_product_code varchar(128),
    declared_document_type varchar(256),
    b9_value varchar(256),
    status varchar(64) not null,
    technical_status varchar(64),
    business_risk varchar(64),
    product_identity_decision varchar(64),
    business_acceptance_decision varchar(64),
    current_stage varchar(64),
    review_version varchar(64) not null,
    idempotency_key varchar(512) not null unique,
    retry_count integer not null default 0,
    result_json text,
    status_detail text,
    created_at timestamp with time zone not null,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    manual_reviewed_at timestamp with time zone,
    version bigint not null default 0
);

create index idx_review_task_hash_version on review_task (file_hash, review_version);
create index idx_review_task_status on review_task (status);
create index idx_review_task_created_at on review_task (created_at);
create index idx_review_task_category on review_task (document_category);
create index idx_review_task_risk on review_task (business_risk);

create table document_page (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    page_number integer not null,
    raw_text text,
    normalized_text text,
    char_count integer not null default 0,
    created_at timestamp with time zone not null,
    constraint fk_document_page_task foreign key (task_id) references review_task(id) on delete cascade,
    constraint uk_document_page_task_page unique (task_id, page_number)
);

create index idx_document_page_task on document_page (task_id);

create table extracted_field (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    field_type varchar(128) not null,
    field_value varchar(1024),
    normalized_value varchar(1024),
    page_number integer,
    sheet_name varchar(256),
    cell_address varchar(64),
    evidence_text text,
    extract_source varchar(64) not null,
    confidence double precision,
    verified boolean not null default false,
    created_at timestamp with time zone not null,
    constraint fk_extracted_field_task foreign key (task_id) references review_task(id) on delete cascade
);

create index idx_extracted_field_task on extracted_field (task_id);
create index idx_extracted_field_type on extracted_field (field_type);

create table model_call_record (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    stage varchar(64) not null,
    provider varchar(128),
    model_name varchar(256),
    prompt_version varchar(64),
    rule_version varchar(64),
    request_summary text,
    raw_response text,
    structured_response text,
    input_char_count integer,
    input_token_count integer,
    output_token_count integer,
    duration_ms bigint,
    call_status varchar(64) not null,
    error_message text,
    created_at timestamp with time zone not null,
    constraint fk_model_call_task foreign key (task_id) references review_task(id) on delete cascade
);

create index idx_model_call_task on model_call_record (task_id);

create table review_issue (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    issue_code varchar(128) not null,
    issue_name varchar(256),
    severity varchar(64),
    confidence double precision,
    page_number integer,
    sheet_name varchar(256),
    cell_address varchar(64),
    evidence_text text,
    evidence_verified boolean not null default false,
    explanation text,
    suggestion text,
    source_type varchar(64),
    rule_code varchar(128),
    model_call_id bigint,
    issue_status varchar(64) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_review_issue_task foreign key (task_id) references review_task(id) on delete cascade,
    constraint fk_review_issue_model_call foreign key (model_call_id) references model_call_record(id)
);

create index idx_review_issue_task on review_issue (task_id);
create index idx_review_issue_status on review_issue (issue_status);

create table manual_review (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    review_decision varchar(64) not null,
    review_comment text,
    ai_result_correct boolean,
    contains_false_positive boolean,
    contains_false_negative boolean,
    actual_issue_types text,
    reviewer varchar(128),
    reviewed_at timestamp with time zone not null,
    constraint fk_manual_review_task foreign key (task_id) references review_task(id) on delete cascade
);

create index idx_manual_review_task on manual_review (task_id);

create table audit_log (
    id bigint generated by default as identity primary key,
    task_id bigint,
    operation_type varchar(128) not null,
    operator varchar(128),
    operation_detail text,
    before_value text,
    after_value text,
    trace_id varchar(128),
    created_at timestamp with time zone not null,
    constraint fk_audit_log_task foreign key (task_id) references review_task(id) on delete set null
);

create index idx_audit_log_task on audit_log (task_id);
create index idx_audit_log_operation on audit_log (operation_type);
create index idx_audit_log_created_at on audit_log (created_at);
