create table review_task_event (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    event_type varchar(128) not null,
    stage varchar(64) not null,
    event_status varchar(64) not null,
    payload_json text,
    retry_count integer not null default 0,
    error_message text,
    created_at timestamp with time zone not null,
    published_at timestamp with time zone,
    completed_at timestamp with time zone,
    version bigint not null default 0,
    constraint fk_review_task_event_task foreign key (task_id) references review_task(id) on delete cascade
);

create index idx_review_task_event_task on review_task_event (task_id);
create index idx_review_task_event_status on review_task_event (event_status);
create index idx_review_task_event_stage on review_task_event (stage);
create index idx_review_task_event_task_stage on review_task_event (task_id, stage, event_type);

create table review_rule_version (
    id bigint generated by default as identity primary key,
    version_code varchar(64) not null unique,
    description text,
    active boolean not null default false,
    created_at timestamp with time zone not null
);

create table review_rule_definition (
    id bigint generated by default as identity primary key,
    rule_code varchar(128) not null unique,
    rule_name varchar(256) not null,
    rule_type varchar(128) not null,
    enabled boolean not null default true,
    severity varchar(64),
    confidence double precision,
    document_types text,
    product_scope text,
    parameters_json text,
    version_code varchar(64) not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create index idx_review_rule_definition_enabled on review_rule_definition (enabled);
create index idx_review_rule_definition_version on review_rule_definition (version_code);

create table review_rule_execution (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    rule_code varchar(128) not null,
    rule_version varchar(64),
    execution_status varchar(64) not null,
    matched boolean not null default false,
    issue_count integer not null default 0,
    duration_ms bigint,
    error_message text,
    created_at timestamp with time zone not null,
    constraint fk_review_rule_execution_task foreign key (task_id) references review_task(id) on delete cascade
);

create index idx_review_rule_execution_task on review_rule_execution (task_id);
create index idx_review_rule_execution_rule on review_rule_execution (rule_code);

create table review_rule_feedback (
    id bigint generated by default as identity primary key,
    task_id bigint not null,
    issue_id bigint,
    rule_code varchar(128),
    feedback_type varchar(64) not null,
    comment text,
    reviewer varchar(128),
    created_at timestamp with time zone not null,
    constraint fk_review_rule_feedback_task foreign key (task_id) references review_task(id) on delete cascade,
    constraint fk_review_rule_feedback_issue foreign key (issue_id) references review_issue(id) on delete set null
);

create index idx_review_rule_feedback_task on review_rule_feedback (task_id);
create index idx_review_rule_feedback_rule on review_rule_feedback (rule_code);

create table llm_provider_config (
    id bigint generated by default as identity primary key,
    provider_code varchar(128) not null unique,
    provider_type varchar(128) not null,
    base_url varchar(1024) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table llm_model_config (
    id bigint generated by default as identity primary key,
    provider_id bigint not null,
    model_code varchar(128) not null unique,
    model_name varchar(256) not null,
    priority integer not null,
    enabled boolean not null default true,
    timeout_seconds integer not null default 120,
    max_retries integer not null default 1,
    temperature double precision not null default 0.1,
    response_format varchar(128) not null default 'json_object',
    api_key_env varchar(256),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_llm_model_provider foreign key (provider_id) references llm_provider_config(id) on delete cascade
);

create index idx_llm_model_enabled_priority on llm_model_config (enabled, priority);

create table llm_call_attempt (
    id bigint generated by default as identity primary key,
    task_id bigint,
    model_config_id bigint,
    provider_code varchar(128),
    model_name varchar(256),
    attempt_order integer not null,
    call_status varchar(64) not null,
    error_message text,
    duration_ms bigint,
    created_at timestamp with time zone not null,
    constraint fk_llm_call_attempt_task foreign key (task_id) references review_task(id) on delete set null,
    constraint fk_llm_call_attempt_model foreign key (model_config_id) references llm_model_config(id) on delete set null
);

create index idx_llm_call_attempt_task on llm_call_attempt (task_id);
create index idx_llm_call_attempt_model on llm_call_attempt (model_config_id);

insert into review_rule_version (version_code, description, active, created_at)
values ('v1', 'Default deterministic rules migrated from code', true, current_timestamp);

insert into review_rule_definition
    (rule_code, rule_name, rule_type, enabled, severity, confidence, document_types, product_scope, parameters_json, version_code, created_at, updated_at)
values
    ('PRODUCT_CODE_EXTRACTION', 'Product code extraction', 'EXTRACTION', true, null, null, null, null, '{}', 'v1', current_timestamp, current_timestamp),
    ('PRODUCT_NAME_EXTRACTION', 'Product name extraction', 'EXTRACTION', true, null, null, null, null, '{}', 'v1', current_timestamp, current_timestamp),
    ('DECLARED_PRODUCT_NOT_FOUND', 'Declared product not found', 'ISSUE', true, 'MEDIUM', 1.0, null, null, '{}', 'v1', current_timestamp, current_timestamp),
    ('CONTENT_LOGIC_CONFLICT', 'Content logic conflict', 'ISSUE', true, 'HIGH', 1.0, null, null, '{}', 'v1', current_timestamp, current_timestamp),
    ('CONTENT_PRODUCT_CODE_CONFLICT', 'Content product code conflict', 'ISSUE', true, 'MEDIUM', 0.5, null, null, '{}', 'v1', current_timestamp, current_timestamp),
    ('POSSIBLE_TEMPLATE_RESIDUE', 'Possible template residue', 'ISSUE', true, 'HIGH', 0.86, null, null, '{}', 'v1', current_timestamp, current_timestamp);

insert into llm_provider_config
    (provider_code, provider_type, base_url, enabled, created_at, updated_at)
values
    ('deepseek-default', 'OPENAI_COMPATIBLE', 'http://localhost:11434/v1', true, current_timestamp, current_timestamp);

insert into llm_model_config
    (provider_id, model_code, model_name, priority, enabled, timeout_seconds, max_retries, temperature, response_format, api_key_env, created_at, updated_at)
select id, 'deepseek-v4-flash-primary', 'deepseek-v4-flash', 10, true, 120, 1, 0.1, 'json_object', null, current_timestamp, current_timestamp
from llm_provider_config
where provider_code = 'deepseek-default';
