create table review_task_context (
    id bigint generated by default as identity primary key,
    task_id bigint not null unique,
    context_json text not null default '{}',
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_review_task_context_task foreign key (task_id) references review_task(id) on delete cascade
);

create index idx_review_task_context_task on review_task_context (task_id);

alter table llm_call_attempt add column if not exists stage varchar(64);
alter table llm_call_attempt add column if not exists operation_type varchar(128);
alter table llm_call_attempt add column if not exists rule_code varchar(128);
alter table llm_call_attempt add column if not exists rule_version_id bigint;
alter table llm_call_attempt add column if not exists chunk_index integer;
alter table llm_call_attempt add column if not exists page_from integer;
alter table llm_call_attempt add column if not exists page_to integer;
alter table llm_call_attempt add column if not exists input_token_count integer;
alter table llm_call_attempt add column if not exists output_token_count integer;
alter table llm_call_attempt add column if not exists cache_hit_token_count integer;
alter table llm_call_attempt add column if not exists raw_usage_json text;

create index if not exists idx_llm_call_attempt_task_stage on llm_call_attempt (task_id, stage);
create index if not exists idx_llm_call_attempt_rule on llm_call_attempt (rule_code, rule_version_id);

alter table model_call_record add column if not exists model_config_id bigint;
alter table model_call_record add column if not exists operation_type varchar(128);
alter table model_call_record add column if not exists rule_code varchar(128);
alter table model_call_record add column if not exists rule_version_id bigint;
alter table model_call_record add column if not exists chunk_index integer;
alter table model_call_record add column if not exists page_from integer;
alter table model_call_record add column if not exists page_to integer;
alter table model_call_record add column if not exists cache_hit_token_count integer;
alter table model_call_record add column if not exists raw_usage_json text;

alter table model_call_record
    add constraint fk_model_call_model_config foreign key (model_config_id)
    references llm_model_config(id) on delete set null;

create index if not exists idx_model_call_task_stage on model_call_record (task_id, stage);
create index if not exists idx_model_call_rule on model_call_record (rule_code, rule_version_id);

alter table review_rule_feedback add column if not exists rule_version_id bigint;
alter table review_rule_feedback add column if not exists rule_execution_id bigint;
alter table review_rule_feedback add column if not exists document_category varchar(64);
alter table review_rule_feedback add column if not exists declared_product_code varchar(128);
alter table review_rule_feedback add column if not exists declared_document_type varchar(256);
alter table review_rule_feedback add column if not exists feedback_source varchar(64);
alter table review_rule_feedback add column if not exists feedback_tags text;
alter table review_rule_feedback add column if not exists aggregation_key varchar(512);
alter table review_rule_feedback add column if not exists process_status varchar(64) not null default 'NEW';
alter table review_rule_feedback add column if not exists issue_snapshot_json text;
alter table review_rule_feedback add column if not exists manual_snapshot_json text;
alter table review_rule_feedback add column if not exists processed_at timestamp with time zone;

create index if not exists idx_review_rule_feedback_process_status on review_rule_feedback (process_status);
create index if not exists idx_review_rule_feedback_aggregation on review_rule_feedback (aggregation_key);
