alter table review_rule_feedback alter column process_status set default 'PENDING';

create table rule_governance_run (
    id bigint generated by default as identity primary key,
    run_no varchar(64) not null unique,
    trigger_type varchar(32) not null,
    status varchar(32) not null,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    scanned_feedback_count integer not null default 0,
    created_group_count integer not null default 0,
    created_proposal_count integer not null default 0,
    failed_group_count integer not null default 0,
    model_config_id bigint,
    input_token_count integer not null default 0,
    output_token_count integer not null default 0,
    cache_hit_token_count integer not null default 0,
    duration_ms bigint,
    error_message text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint fk_rule_governance_run_model foreign key (model_config_id)
        references llm_model_config(id) on delete set null
);

create table rule_feedback_governance_group (
    id bigint generated by default as identity primary key,
    group_key varchar(768) not null,
    rule_definition_id bigint,
    rule_code varchar(128) not null,
    rule_version_id bigint not null,
    rule_version varchar(64) not null,
    feedback_type varchar(64) not null,
    document_category varchar(64),
    declared_file_type varchar(256),
    product_series varchar(256),
    issue_type varchar(128),
    status varchar(32) not null,
    feedback_count integer not null default 0,
    representative_feedback_id bigint,
    latest_feedback_at timestamp with time zone,
    governance_run_id bigint not null,
    error_message text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint fk_governance_group_rule foreign key (rule_definition_id)
        references review_rule_definition(id) on delete set null,
    constraint fk_governance_group_rule_version foreign key (rule_version_id)
        references review_rule_version(id),
    constraint fk_governance_group_representative foreign key (representative_feedback_id)
        references review_rule_feedback(id) on delete set null,
    constraint fk_governance_group_run foreign key (governance_run_id)
        references rule_governance_run(id) on delete cascade
);

create index idx_governance_group_key_status
    on rule_feedback_governance_group (group_key, status);
create index idx_governance_group_run
    on rule_feedback_governance_group (governance_run_id);

create table rule_feedback_governance_group_item (
    id bigint generated by default as identity primary key,
    group_id bigint not null,
    feedback_id bigint not null unique,
    created_at timestamp with time zone not null,
    constraint fk_governance_group_item_group foreign key (group_id)
        references rule_feedback_governance_group(id) on delete cascade,
    constraint fk_governance_group_item_feedback foreign key (feedback_id)
        references review_rule_feedback(id) on delete cascade,
    constraint uk_governance_group_item unique (group_id, feedback_id)
);

create table rule_change_proposal (
    id bigint generated by default as identity primary key,
    proposal_no varchar(64) not null unique,
    proposal_type varchar(64) not null,
    proposal_status varchar(64) not null,
    governance_group_id bigint not null,
    governance_run_id bigint not null,
    rule_definition_id bigint,
    rule_code varchar(128),
    source_rule_version_id bigint,
    source_rule_version varchar(64),
    root_cause_type varchar(64) not null,
    agent_confidence double precision,
    problem_summary text,
    root_cause_analysis text,
    change_reason text,
    expected_effect text,
    risk_description text,
    before_rule_snapshot_json text,
    after_rule_snapshot_json text,
    final_rule_snapshot_json text,
    change_content_json text,
    validation_result_json text,
    backtest_result_json text,
    affected_scope_json text,
    optimization_category varchar(64),
    optimization_advice text,
    responsible_module varchar(128),
    proposal_priority varchar(32),
    human_follow_up_required boolean not null default false,
    agent_model_config_id bigint,
    agent_provider varchar(128),
    agent_model varchar(256),
    agent_prompt_version varchar(64),
    agent_response_json text,
    draft_rule_definition_id bigint,
    draft_rule_version_id bigint,
    submitted_at timestamp with time zone,
    reviewed_at timestamp with time zone,
    applied_at timestamp with time zone,
    closed_at timestamp with time zone,
    deferred_until timestamp with time zone,
    defer_reason text,
    created_by varchar(128),
    reviewed_by varchar(128),
    review_comment text,
    rejection_reason varchar(64),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    version bigint not null default 0,
    constraint fk_rule_change_proposal_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id),
    constraint fk_rule_change_proposal_run foreign key (governance_run_id)
        references rule_governance_run(id),
    constraint fk_rule_change_proposal_rule foreign key (rule_definition_id)
        references review_rule_definition(id) on delete set null,
    constraint fk_rule_change_proposal_source_version foreign key (source_rule_version_id)
        references review_rule_version(id) on delete set null,
    constraint fk_rule_change_proposal_model foreign key (agent_model_config_id)
        references llm_model_config(id) on delete set null,
    constraint fk_rule_change_proposal_draft_rule foreign key (draft_rule_definition_id)
        references review_rule_definition(id) on delete set null,
    constraint fk_rule_change_proposal_draft_version foreign key (draft_rule_version_id)
        references review_rule_version(id) on delete set null
);

create index idx_rule_change_proposal_group_status
    on rule_change_proposal (governance_group_id, proposal_status);
create index idx_rule_change_proposal_rule
    on rule_change_proposal (rule_code, source_rule_version_id);

create table rule_change_proposal_feedback (
    id bigint generated by default as identity primary key,
    proposal_id bigint not null,
    feedback_id bigint not null,
    created_at timestamp with time zone not null,
    constraint fk_proposal_feedback_proposal foreign key (proposal_id)
        references rule_change_proposal(id) on delete cascade,
    constraint fk_proposal_feedback_feedback foreign key (feedback_id)
        references review_rule_feedback(id) on delete cascade,
    constraint uk_proposal_feedback unique (proposal_id, feedback_id)
);

create table rule_governance_memory (
    id bigint generated by default as identity primary key,
    memory_type varchar(32) not null,
    rule_code varchar(128),
    rule_version varchar(64),
    document_category varchar(64),
    declared_file_type varchar(256),
    root_cause_type varchar(64),
    proposal_type varchar(64),
    proposal_id bigint,
    governance_group_id bigint,
    decision varchar(64) not null,
    decision_reason text,
    human_comment text,
    case_summary text,
    agent_suggestion_summary text,
    final_change_summary text,
    before_rule_snapshot_json text,
    final_rule_snapshot_json text,
    backtest_summary_json text,
    effect_summary_json text,
    source_type varchar(64),
    source_id bigint,
    enabled boolean not null default true,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_rule_governance_memory_proposal foreign key (proposal_id)
        references rule_change_proposal(id) on delete set null,
    constraint fk_rule_governance_memory_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id) on delete set null
);

create index idx_governance_memory_search
    on rule_governance_memory (rule_code, document_category, declared_file_type, root_cause_type, enabled);

create table rule_governance_tool_call (
    id bigint generated by default as identity primary key,
    governance_run_id bigint not null,
    governance_group_id bigint not null,
    proposal_id bigint,
    iteration_number integer not null,
    tool_name varchar(128) not null,
    argument_hash varchar(64) not null,
    candidate_hash varchar(64),
    input_json text,
    output_json text,
    call_status varchar(32) not null,
    error_message text,
    duration_ms bigint,
    created_at timestamp with time zone not null,
    constraint fk_governance_tool_call_run foreign key (governance_run_id)
        references rule_governance_run(id) on delete cascade,
    constraint fk_governance_tool_call_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id) on delete cascade,
    constraint fk_governance_tool_call_proposal foreign key (proposal_id)
        references rule_change_proposal(id) on delete set null
);

create index idx_governance_tool_call_lookup
    on rule_governance_tool_call (governance_run_id, governance_group_id, tool_name, argument_hash);

create table rule_governance_event (
    id bigint generated by default as identity primary key,
    governance_run_id bigint not null,
    governance_group_id bigint not null,
    event_type varchar(64) not null,
    event_status varchar(32) not null,
    payload_json text,
    retry_count integer not null default 0,
    error_message text,
    created_at timestamp with time zone not null,
    published_at timestamp with time zone,
    completed_at timestamp with time zone,
    version bigint not null default 0,
    constraint fk_governance_event_run foreign key (governance_run_id)
        references rule_governance_run(id) on delete cascade,
    constraint fk_governance_event_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id) on delete cascade
);

create index idx_governance_event_status_created
    on rule_governance_event (event_status, created_at);
create index idx_governance_event_group
    on rule_governance_event (governance_group_id, event_type, event_status);

alter table review_rule_version add column if not exists source_proposal_id bigint;
alter table review_rule_version
    add constraint fk_rule_version_source_proposal foreign key (source_proposal_id)
        references rule_change_proposal(id) on delete set null;

alter table llm_call_attempt add column if not exists governance_run_id bigint;
alter table llm_call_attempt add column if not exists governance_group_id bigint;
alter table llm_call_attempt add column if not exists governance_proposal_id bigint;
alter table llm_call_attempt add column if not exists prompt_version varchar(64);
alter table llm_call_attempt
    add constraint fk_llm_attempt_governance_run foreign key (governance_run_id)
        references rule_governance_run(id) on delete set null;
alter table llm_call_attempt
    add constraint fk_llm_attempt_governance_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id) on delete set null;
alter table llm_call_attempt
    add constraint fk_llm_attempt_governance_proposal foreign key (governance_proposal_id)
        references rule_change_proposal(id) on delete set null;

alter table model_call_record alter column task_id drop not null;
alter table model_call_record add column if not exists governance_run_id bigint;
alter table model_call_record add column if not exists governance_group_id bigint;
alter table model_call_record add column if not exists governance_proposal_id bigint;
alter table model_call_record
    add constraint fk_model_call_governance_run foreign key (governance_run_id)
        references rule_governance_run(id) on delete set null;
alter table model_call_record
    add constraint fk_model_call_governance_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id) on delete set null;
alter table model_call_record
    add constraint fk_model_call_governance_proposal foreign key (governance_proposal_id)
        references rule_change_proposal(id) on delete set null;

alter table audit_log add column if not exists governance_run_id bigint;
alter table audit_log add column if not exists governance_group_id bigint;
alter table audit_log add column if not exists proposal_id bigint;
alter table audit_log add column if not exists rule_code varchar(128);
alter table audit_log add column if not exists source_feedback_ids text;
alter table audit_log
    add constraint fk_audit_governance_run foreign key (governance_run_id)
        references rule_governance_run(id) on delete set null;
alter table audit_log
    add constraint fk_audit_governance_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id) on delete set null;
alter table audit_log
    add constraint fk_audit_governance_proposal foreign key (proposal_id)
        references rule_change_proposal(id) on delete set null;

create index idx_audit_governance_proposal on audit_log (proposal_id, created_at);
create index idx_llm_attempt_governance on llm_call_attempt (governance_run_id, governance_group_id);
create index idx_model_call_governance on model_call_record (governance_run_id, governance_group_id);
