alter table rule_governance_run
    add column if not exists trace_id varchar(64);

update rule_governance_run
set trace_id = 'governance-run-' || id
where trace_id is null;

alter table rule_governance_run
    alter column trace_id set not null;

create unique index if not exists uk_rule_governance_run_trace_id
    on rule_governance_run (trace_id);

create table if not exists rule_governance_trace_span (
    id bigint generated by default as identity primary key,
    trace_id varchar(64) not null,
    span_id varchar(96) not null unique,
    parent_span_id varchar(96),
    governance_run_id bigint not null,
    governance_group_id bigint,
    span_type varchar(32) not null,
    span_name varchar(160) not null,
    execution_mode varchar(16) not null default 'SERIAL',
    parallel_group varchar(96),
    sequence_no integer,
    iteration_number integer,
    span_status varchar(32) not null,
    provider_code varchar(128),
    model_name varchar(256),
    input_token_count integer not null default 0,
    output_token_count integer not null default 0,
    cache_hit_token_count integer not null default 0,
    duration_ms bigint,
    error_message text,
    attributes_json text,
    started_at timestamp with time zone not null,
    finished_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_governance_trace_run foreign key (governance_run_id)
        references rule_governance_run(id) on delete cascade,
    constraint fk_governance_trace_group foreign key (governance_group_id)
        references rule_feedback_governance_group(id) on delete cascade
);

create index if not exists idx_governance_trace_run_started
    on rule_governance_trace_span (governance_run_id, started_at, id);
create index if not exists idx_governance_trace_parent
    on rule_governance_trace_span (trace_id, parent_span_id);
create index if not exists idx_governance_trace_group
    on rule_governance_trace_span (governance_group_id, started_at);
